# Generated by Django 2.2.4 on 2024-04-17 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='additional_field3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
