# Generated by Django 2.2.4 on 2024-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240417_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='por',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_inc_vat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vat',
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_date_time',
            field=models.DateField(),
        ),
    ]
