# Generated by Django 2.2.4 on 2024-04-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240417_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pack_size',
        ),
    ]
